#ifndef CHRIS_SH_SRC_H
#define CHRIS_SH_SRC_H
/* Generated from kernel/gfx/shader/glsl. ChrisOS GLSL subset, not GLSL 3.30. */
static const char SH_SRC_TRI_VERT[] = "#version 330\nlayout(location = 0) in vec4 position;\nlayout(location = 1) in vec4 color;\nout vec4 vcolor;\nvoid main() {\n    vcolor = color;\n    gl_Position = position;\n}\n";
static const char SH_SRC_TRI_FRAG[] = "#version 330\nin vec4 vcolor;\nout vec4 fragColor;\nvoid main() {\n    fragColor = vcolor;\n}\n";
static const char SH_SRC_VARY_VERT[] = "#version 330\nlayout(location = 0) in vec4 position;\nlayout(location = 1) in vec3 vertexColor;\nout vec3 color;\nvoid main() {\n    color = vertexColor;\n    gl_Position = position;\n}\n";
static const char SH_SRC_VARY_FRAG[] = "#version 330\nin vec3 color;\nout vec4 fragColor;\nvoid main() {\n    fragColor = vec4(color, 1.0);\n}\n";
static const char SH_SRC_MVP_VERT[] = "#version 330\nlayout(location = 0) in vec4 position;\nlayout(location = 1) in vec4 color;\nuniform mat4 model;\nuniform mat4 view;\nuniform mat4 projection;\nout vec4 vcolor;\nvoid main() {\n    vcolor = color;\n    gl_Position = projection * view * model * position;\n}\n";
static const char SH_SRC_TEX_VERT[] = "#version 330\nlayout(location = 0) in vec4 position;\nlayout(location = 1) in vec2 uv;\nuniform mat4 model;\nuniform mat4 view;\nuniform mat4 projection;\nout vec2 fragUV;\nvoid main() {\n    fragUV = uv;\n    gl_Position = projection * view * model * position;\n}\n";
static const char SH_SRC_TEX_FRAG[] = "#version 330\nin vec2 fragUV;\nuniform sampler2D diffuseTexture;\nout vec4 color;\nvoid main() {\n    color = texture(diffuseTexture, fragUV);\n}\n";
static const char SH_SRC_LIGHT_VERT[] = "#version 330\nlayout(location = 0) in vec3 position;\nlayout(location = 1) in vec3 normal;\nuniform mat4 model;\nuniform mat4 view;\nuniform mat4 projection;\nout vec3 vN;\nout vec3 vP;\nvoid main() {\n    vec4 world = model * vec4(position, 1.0);\n    vP = world.xyz;\n    vN = normal;\n    gl_Position = projection * view * world;\n}\n";
static const char SH_SRC_LIGHT_FRAG[] = "#version 330\nin vec3 vN;\nin vec3 vP;\nuniform vec3 lightPosition;\nuniform vec3 lightColor;\nuniform vec3 ambientColor;\nout vec4 color;\nvoid main() {\n    vec3 N = normalize(vN);\n    vec3 L = normalize(lightPosition - vP);\n    float diffuse = max(dot(N, L), 0.0);\n    vec3 result = ambientColor + diffuse * lightColor;\n    color = vec4(result, 1.0);\n}\n";
static const char SH_SRC_WORLD_VERT[] = "#version 330\nlayout(location = 0) in vec3 position;\nlayout(location = 1) in vec3 normal;\nlayout(location = 2) in vec2 uv;\nuniform mat4 model;\nuniform mat4 view;\nuniform mat4 projection;\nuniform mat3 normalMatrix;\nout vec3 vN;\nout vec3 vP;\nout vec2 vUV;\nvoid main() {\n    vec4 world = model * vec4(position, 1.0);\n    vP = world.xyz;\n    vN = normalize(normalMatrix * normal);\n    vUV = uv;\n    gl_Position = projection * view * world;\n}\n";
static const char SH_SRC_WORLD_FRAG[] = "#version 330\nin vec3 vN;\nin vec3 vP;\nin vec2 vUV;\nuniform sampler2D diffuseTexture;\nuniform vec3 lightPosition;\nuniform vec3 lightColor;\nuniform vec3 ambientColor;\nout vec4 color;\nvoid main() {\n    vec3 N = normalize(vN);\n    vec3 L = normalize(lightPosition - vP);\n    float diffuse = max(dot(N, L), 0.0);\n    vec3 result = ambientColor + diffuse * lightColor;\n    color = texture(diffuseTexture, vUV) * vec4(result, 1.0);\n}\n";
#endif
