#ifndef CHRIS_VIRGL_PROTO_H
#define CHRIS_VIRGL_PROTO_H

#include <stdint.h>

/*
 * Subset of the VirGL command stream from virglrenderer 1.0.0
 * src/virgl_protocol.h (VIRGL_CMD0 and the command numbers below).
 * Gallium clear/prim/shader values used by that encoder:
 *   PIPE_CLEAR_COLOR0 = 1<<2, PIPE_PRIM_TRIANGLES = 4,
 *   PIPE_SHADER_VERTEX = 0, PIPE_SHADER_FRAGMENT = 1.
 */

#define VIRGL_CMD0(cmd, obj, len) \
    ((uint32_t)(cmd) | ((uint32_t)(obj) << 8) | ((uint32_t)(len) << 16))

#define VIRGL_CCMD_CREATE_OBJECT 1u
#define VIRGL_CCMD_BIND_OBJECT 2u
#define VIRGL_CCMD_DESTROY_OBJECT 3u
#define VIRGL_CCMD_SET_VIEWPORT_STATE 4u
#define VIRGL_CCMD_SET_FRAMEBUFFER_STATE 5u
#define VIRGL_CCMD_SET_VERTEX_BUFFERS 6u
#define VIRGL_CCMD_CLEAR 7u
#define VIRGL_CCMD_DRAW_VBO 8u
#define VIRGL_CCMD_SET_SAMPLER_VIEWS 10u
#define VIRGL_CCMD_SET_INDEX_BUFFER 11u
#define VIRGL_CCMD_SET_CONSTANT_BUFFER 12u
#define VIRGL_CCMD_BIND_SAMPLER_STATES 18u
#define VIRGL_CCMD_BIND_SHADER 31u
#define VIRGL_CCMD_LINK_SHADER 52u

#define VIRGL_OBJECT_BLEND 1u
#define VIRGL_OBJECT_RASTERIZER 2u
#define VIRGL_OBJECT_DSA 3u
#define VIRGL_OBJECT_SHADER 4u
#define VIRGL_OBJECT_VERTEX_ELEMENTS 5u
#define VIRGL_OBJECT_SAMPLER_VIEW 6u
#define VIRGL_OBJECT_SAMPLER_STATE 7u
#define VIRGL_OBJECT_SURFACE 8u

#define VIRGL_OBJ_BLEND_SIZE 11u
#define VIRGL_OBJ_DSA_SIZE 5u
#define VIRGL_OBJ_RS_SIZE 9u
#define VIRGL_OBJ_CLEAR_SIZE 8u
#define VIRGL_OBJ_SURFACE_SIZE 5u
#define VIRGL_OBJ_SAMPLER_STATE_SIZE 9u
#define VIRGL_OBJ_SAMPLER_VIEW_SIZE 6u
#define VIRGL_LINK_SHADER_SIZE 6u
#define VIRGL_DRAW_VBO_SIZE 12u

#define VIRGL_FORMAT_B8G8R8A8_UNORM 1u
#define VIRGL_FORMAT_Z32_FLOAT 18u
#define VIRGL_FORMAT_R32G32_FLOAT 29u
#define VIRGL_FORMAT_R32G32B32A32_FLOAT 31u
#define VIRGL_FORMAT_R8_UNORM 64u

#define VIRGL_BIND_DEPTH_STENCIL (1u << 0)
#define VIRGL_BIND_RENDER_TARGET (1u << 1)
#define VIRGL_BIND_SAMPLER_VIEW (1u << 3)
#define VIRGL_BIND_VERTEX_BUFFER (1u << 4)
#define VIRGL_BIND_INDEX_BUFFER (1u << 5)
#define VIRGL_BIND_DISPLAY_TARGET (1u << 7)
#define VIRGL_BIND_SCANOUT (1u << 18)

#define VIRGL_TARGET_BUFFER 0u
#define VIRGL_TARGET_TEXTURE_2D 2u

#define VIRGL_CLEAR_COLOR0 (1u << 2)
#define VIRGL_PRIM_TRIANGLES 4u
#define VIRGL_SHADER_VERTEX 0u
#define VIRGL_SHADER_FRAGMENT 1u

#define VIRGL_F32_ONE 0x3f800000u
#define VIRGL_F32_HALF 0x3f000000u

#endif
